# Use the official Node.js image with Alpine Linux for a smaller footprint
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) first to leverage Docker's cache
COPY package.json ./
COPY package-lock.json ./

# Install the app dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose port 3000 (React's default port)
EXPOSE 3000

# Start the development server
CMD ["npm", "run","start"]
